### ISSUE TITLE
underlying algorithm

### ISSUE THREAD

**Issue by usergoodvery** [darkautism/lfqueue#5]
Hi
Thanks for sharing this. What is the underlying algorithm for this code? Is there any formal proof?

regards

**Comment by darkautism** [comment]
Hi usergoodvery,

HP : [Paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.395.378&rep=rep1&type=pdf)
FSHW: Custom design spinlock queue
experimental-DCAS: Somebody say double compare and swap can impilement lockfree queue, but i still cannot image this one. This is an abandon branch
